app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('first/',first,name='first')
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('second/',second,name='second'),
]

urlnavigation/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
from app3.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('third/',third,name='third')
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request,'first.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def second(request):
    return render(request,'second.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def third(request):
    return render(request,'third.html')

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <center>
    <h1>my name is abbulu</h1>
    <a href="{% url 'app2:second' %}">Click here</a>
   </center> 
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>DELL</h1>
    <a href="{% url 'third' %}">ClickHere</a>
</body>
</html>

templates/third.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>TEMPLATES</h1>
<a href="{% url 'app1:first' %}">Click Herer</a>
</body>
</html>